import Nav from "./components/navbar"
import Footer from "./components/footer"
import Styles from './styles/layout.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (

    <html lang="en">
     

      <body>
        <Nav></Nav>
  
        {children}
      <Footer></Footer>
        </body>
    </html>
  )
}
